version: "3.8"
services:
  frontend:
    build: ./front
    container_name: frontend_c
    ports:
      - '3000:3000'
  backend:  
    build: ./backend
    container_name: backend_c
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true